### ISSUE TITLE
Error: Cannot find module './tables'

### ISSUE THREAD

**Issue by ruediger** [dherman/asm.js#50]
The validator seems to be broken.  First of all the `package.json` file says `"main": "lib/asm.js"` but `asm.js` is in `tests/` and not `lib/`.  After moving the file to `lib/` I get the following error message

```
Error: Cannot find module './tables'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/ruediger/develop/demos/node/node_modules/asm.js/lib/validate.js:8:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

The require is in `validate.js`: `var tables = require('./tables');`.  But there is no `tables.js` available.  The problems seem to have been introduced in 182e4b9efe556f205e33be1f9357938a41ebbbe3

**Comment by sunfishcode** [comment]
lib/asm.js and lib/tables.js now exist, and the validator now appears to find them.
